version: '3'

services:
  browser-agent:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browser-agent
    ports:
      - "5001:5001"  # API
      - "6080:6080"  # noVNC
      - "9222:9222"  # Chrome Debugger
      - "5900:5900"  # VNC (optional)
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENABLE_METRICS_SERVER=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - AGENT_TIMEOUT=${AGENT_TIMEOUT:-300}
      - AGENT_MAX_STEPS=${AGENT_MAX_STEPS:-30}
      - MAX_BROWSER_INSTANCES=${MAX_BROWSER_INSTANCES:-5}
    volumes:
      - ./duplo_logs:/app/duplo_logs
    networks:
      - browser-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - browser-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - browser-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - loki
    networks:
      - browser-network
    restart: unless-stopped

volumes:
  grafana-data:

networks:
  browser-network:
    driver: bridge